In [1]:
#pandas

In [ ]:
dict
 
    
    
keys value Pairs

id=
name=
email=


matplotlib = plots
seaborne = plots
pandas = data manipulation

In [3]:
#series and dataframe

In [ ]:
import pandas as pd

In [11]:
import pandas as pd
num=pd.Series([7,71,8,9,10,11])
print(num)
print(type(num))

0     7
1    71
2     8
3     9
4    10
5    11
dtype: int64
<class 'pandas.core.series.Series'>


In [10]:
import pandas as pd
char=pd.Series(['a','b','c','d',7])
print(char)
print(type(char))

0    a
1    b
2    c
3    d
4    7
dtype: object
<class 'pandas.core.series.Series'>


In [14]:
date=pd.date_range(start='21-07-2021',end='30-7-2021')
print(date,type(date))

DatetimeIndex(['2021-07-21', '2021-07-22', '2021-07-23', '2021-07-24',
               '2021-07-25', '2021-07-26', '2021-07-27', '2021-07-28',
               '2021-07-29', '2021-07-30'],
              dtype='datetime64[ns]', freq='D') <class 'pandas.core.indexes.datetimes.DatetimeIndex'>


In [26]:
import pandas as pd
date1=pd.date_range(start='1-01-2021',end='1-04-2021')
print(date1)

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04'], dtype='datetime64[ns]', freq='D')


In [15]:
#Data frames

In [28]:
df=pd.DataFrame({'Month':['jan','feb','mar'],
                   'Temp': [25,23,45]})
print(df)

  Month  Temp
0   jan    25
1   feb    23
2   mar    45


In [14]:
import pandas as pd
df=pd.DataFrame({'Month':['jan','feb','mar'],
                   'Temp': [25,23,45]})
df['Month']
print(df)
print(df['Month'][2],df['Temp'][2])

  Month  Temp
0   jan    25
1   feb    23
2   mar    45
mar 45


In [30]:
import pandas as pd
sample=pd.read_csv(r"C:\Users\Admin\Desktop\pavan\Ignited tech\simple.csv")
print(sample)
print(sample.head)
print(sample.tail)
print(sample.info)
print(sample.describe)
print(sample.columns)
print(sample.shape)
print(sample.values)

     Month  Temp
0      jan    25
1      feb    23
2      mar    45
<bound method NDFrame.head of      Month  Temp
0      jan    25
1      feb    23
2      mar    45>
<bound method NDFrame.tail of      Month  Temp
0      jan    25
1      feb    23
2      mar    45>
<bound method DataFrame.info of      Month  Temp
0      jan    25
1      feb    23
2      mar    45>
<bound method NDFrame.describe of      Month  Temp
0      jan    25
1      feb    23
2      mar    45>
Index(['   Month  Temp'], dtype='object')
(3, 1)
[['   jan    25']
 ['   feb    23']
 ['   mar    45']]


In [1]:
import pandas as pd

In [2]:
t=pd.Series([1.1,2,3,4])
print(t)

0    1.1
1    2.0
2    3.0
3    4.0
dtype: float64


In [3]:
for i in t.values:
    print(i)

1.1
2.0
3.0
4.0


In [4]:
for i in t.index:
    print(i)

0
1
2
3


In [5]:
mercury=pd.Series([0.1,0.3,0.5],index=['mass','diameter','density'])
print(mercury)

mass        0.1
diameter    0.3
density     0.5
dtype: float64


In [6]:
mercury=pd.Series([0.1,0.3,0.5],index=['mass','diameter','density'])

a=mercury['mass']
print(a)

0.1


In [ ]:
#converting dict to series

In [9]:
d={}
d['mass']=0.1
d['dia']=0.2
d['den']=0.3
print(d)
print(type(d))

mercury=pd.Series(d)
print(mercury)

{'mass': 0.1, 'dia': 0.2, 'den': 0.3}
<class 'dict'>
mass    0.1
dia     0.2
den     0.3
dtype: float64


In [10]:
#loc and iloc

In [ ]:
location and implicit location

In [11]:
mercury=pd.Series([0.1,0.3,0.5],index=['mass','diameter','density'])
print(mercury)

mass        0.1
diameter    0.3
density     0.5
dtype: float64


In [20]:
l=mercury.loc['mass']
print(l)
i=mercury.iloc[1]#not allows characters
print(i)

0.1
0.3


In [ ]:
#simple operations

In [1]:
import pandas as pd
mass=pd.Series([0.33,4.87,5.97,0.642,1898,568,86.8,102,0.0146],index=['Mercury','Venus','Earth','Mars','jupiter','Saturn','Uranus','Neptune','Plito'])
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Plito         0.0146
dtype: float64


In [22]:
print(mass[1])

4.87


In [23]:
print(mass.iloc[1])

4.87


In [25]:
print(mass.loc["Venus"])

4.87


In [27]:
print(mass<100)

Mercury     True
Venus       True
Earth       True
Mars        True
jupiter    False
Saturn     False
Uranus      True
Neptune    False
Plito       True
dtype: bool


In [28]:
print(mass[mass>100])

jupiter    1898.0
Saturn      568.0
Neptune     102.0
dtype: float64


In [2]:
print(mass*2)

Mercury       0.6600
Venus         9.7400
Earth        11.9400
Mars          1.2840
jupiter    3796.0000
Saturn     1136.0000
Uranus      173.6000
Neptune     204.0000
Plito         0.0292
dtype: float64


In [3]:
for i in mass.values():
    if mass.values=="Nan":
        print("0")
    else:
        print("Nan")

TypeError: 'numpy.ndarray' object is not callable

In [40]:
big_mass=mass*mass
print(big_mass)

Mercury    1.089000e-01
Venus      2.371690e+01
Earth      3.564090e+01
Mars       4.121640e-01
jupiter    3.602404e+06
Saturn     3.226240e+05
Uranus     7.534240e+03
Neptune    1.040400e+04
Plito      2.131600e-04
dtype: float64


In [4]:
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Plito         0.0146
dtype: float64


In [5]:
mass['moon']=66
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Plito         0.0146
moon         66.0000
dtype: float64


In [ ]:
#Creating data frame objects

In [6]:
import numpy as np
import pandas as pd

In [14]:
arr=np.random.randint(30,44,(4,3))
print(arr)

[[31 30 42]
 [35 30 43]
 [32 35 43]
 [36 40 37]]


In [17]:
df=pd.DataFrame(arr)
print(df)

    0   1   2
0  31  30  42
1  35  30  43
2  32  35  43
3  36  40  37


In [18]:
print(df.values)

[[31 30 42]
 [35 30 43]
 [32 35 43]
 [36 40 37]]


In [19]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)


In [21]:
print(df.items)

<bound method DataFrame.items of     0   1   2
0  31  30  42
1  35  30  43
2  32  35  43
3  36  40  37>


In [23]:
for i in df.columns:
    print(i)

0
1
2


In [36]:
import numpy as np
import pandas as pd
arr=np.random.randint(30,44,(4,3))
print(arr)
df=pd.DataFrame(arr)
print(df)
df.index=['a','b','c','d']
df.columns=['11','12','13']
print(df)
#print(df.index)

[[37 41 39]
 [34 35 34]
 [41 40 39]
 [30 30 42]]
    0   1   2
0  37  41  39
1  34  35  34
2  41  40  39
3  30  30  42
   11  12  13
a  37  41  39
b  34  35  34
c  41  40  39
d  30  30  42


In [52]:
import seaborn as sns
df=sns.load_dataset('planets')
print(df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009


In [53]:
import numpy as np
import pandas as pd
print(df.tail())
print(df.describe)
print(df.info)

       method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008
<bound method NDFrame.describe of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN  

In [ ]:
#slicing and dicing of dataframes

In [1]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("global_sales_data/market_fact.csv")
print(df)

        Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1                 13     4.56      

In [9]:
print(df.head)
print(df.tail)

<bound method NDFrame.head of         Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1    

In [10]:
print(df.Sales>5000)

0       False
1       False
2       False
3       False
4       False
        ...  
8394    False
8395    False
8396    False
8397    False
8398    False
Name: Sales, Length: 8399, dtype: bool


In [11]:
print(df.Cust_id)

0       Cust_1818
1       Cust_1818
2       Cust_1818
3       Cust_1818
4       Cust_1818
          ...    
8394    Cust_1798
8395    Cust_1798
8396    Cust_1798
8397    Cust_1798
8398    Cust_1798
Name: Cust_id, Length: 8399, dtype: object


In [15]:
print(df.loc[df['Sales']>40000,:])


        Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
1835  Ord_3875  Prod_17  SHP_5370  Cust_1351  41343.21      0.09   
2738  Ord_3084  Prod_17  SHP_4279  Cust_1151  89061.05      0.00   
3784  Ord_2338  Prod_17  SHP_3207   Cust_932  45923.76      0.07   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  
1835               8   3852.19          24.49                 0.39  
2738              13  27220.69          24.49                 0.39  
3784               7    102.61          24.49                 0.39  


In [16]:
print(df.loc[(df.Sales>2000)] and (df.Sales>40000) and (df.Sales>10000))

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [19]:
df.loc[(df.Sales!=10000)]

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1                 13     4.56           0.93                 0.54  
2                 26  1148.90           2.50                 0.59  
3                 43   729.34          14.30                 0.37  
4                 35  1219.87          26.30                 0.38  
...              ...      ...            ...                  ...  
8394              28   374.63           7.69                 0.59  
8395              20   -74.03           6.92                 0.37  
8396              39   -70.85           5.35                 0.40  
8397              23   565.34          30.00                 0.62  
8398              47   131.39           4.86                 0.38  

[8399 rows x 10 columns]

In [21]:
customer_in_bangalore=['Cust_1798','Cust_1818',]
print(df.loc[df['Cust_id'].isin(customer_in_bangalore)])


        Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
5     Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
8390  Ord_5435  Prod_16  SHP_7594  Cust_1798   316.9900      0.04   
8391  Ord_5435   Prod_4  SHP_7594  Cust_1798  1991.8985      0.07   
8392  Ord_5384   Prod_9  SHP_7519  Cust_1798   181.5000      0.08   
8393  Ord_5348   Prod_8  SHP_7470  Cust_1798   356.7200      0.07   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469 

In [23]:
a=df.copy()
print(a.head)

<bound method NDFrame.head of         Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1    

In [24]:
#Merging and Concatenating

# Merging

In [33]:
import pandas as pd
import numpy as np
a1=pd.read_csv("global_sales_data/cust_dimen.csv")
print(a1.Cust_id)
a2=pd.read_csv("global_sales_data/market_fact.csv")
print(a2.Cust_id.head())
customer=pd.merge(a1,a2,how='inner',on='Cust_id')
print(customer.Cust_id)

0          Cust_1
1          Cust_2
2          Cust_3
3          Cust_4
4          Cust_5
          ...    
1827    Cust_1828
1828    Cust_1829
1829    Cust_1830
1830    Cust_1831
1831    Cust_1832
Name: Cust_id, Length: 1832, dtype: object
0    Cust_1818
1    Cust_1818
2    Cust_1818
3    Cust_1818
4    Cust_1818
Name: Cust_id, dtype: object
0          Cust_1
1          Cust_2
2          Cust_2
3          Cust_3
4          Cust_3
          ...    
8394    Cust_1831
8395    Cust_1831
8396    Cust_1832
8397    Cust_1832
8398    Cust_1832
Name: Cust_id, Length: 8399, dtype: object


# Concatenating

In [6]:
import pandas as pd
import numpy as np
 
df1=pd.DataFrame({'Name':['Pavan','Nayan','Naveeni'],
                  'Age':[21,23,24],
                  'Gender':['M','M','F']})
df2=pd.DataFrame({'Name':['Harsha','Nayaki'],
                  'Age':[21,25],
                  'Gender':['M','F']})
a=pd.concat([df1,df2],axis=0)
print(a)


      Name  Age Gender
0    Pavan   21      M
1    Nayan   23      M
2  Naveeni   24      F
0   Harsha   21      M
1   Nayaki   25      F


# Grouping and Summeraizing

In [7]:
import pandas as pd
import numpy as np

In [8]:
market_df=pd.read_csv("global_sales_data/market_fact.csv")
customer_df=pd.read_csv("global_sales_data/cust_dimen.csv")
order_df=pd.read_csv("global_sales_data/orders_dimen.csv")
product_df=pd.read_csv("global_sales_data/prod_dimen.csv")
shipping_df=pd.read_csv("global_sales_data/shipping_dimen.csv")



In [13]:
#bussiness analysis on customer segments,regions product categories

df1=pd.merge(market_df,customer_df,how='inner',on='Cust_id')

df2=pd.merge(df1,product_df,how='inner',on='Prod_id')

df3=pd.merge(df2,shipping_df,how='inner',on='Ship_id')

master_df =pd.merge(df3,order_df,how='inner',on='Ord_id')

print(master_df.info)

<bound method DataFrame.info of         Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818    136.81      0.01   
1     Ord_5446   Prod_4  SHP_7610  Cust_1818   4701.69      0.00   
2     Ord_5446   Prod_6  SHP_7608  Cust_1818    164.02      0.03   
3     Ord_2978  Prod_16  SHP_4112  Cust_1088    305.05      0.04   
4     Ord_5484  Prod_16  SHP_7663  Cust_1820    322.82      0.05   
...        ...      ...       ...        ...       ...       ...   
8394  Ord_5018  Prod_14  SHP_7001  Cust_1696   7325.63      0.04   
8395   Ord_669  Prod_14   SHP_916   Cust_224  20872.16      0.03   
8396   Ord_508  Prod_14   SHP_686   Cust_186  19109.61      0.10   
8397  Ord_3721  Prod_14  SHP_5162  Cust_1309    614.14      0.09   
8398   Ord_825  Prod_14  SHP_1132   Cust_247  27663.92      0.05   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  ...  \
0                 23   -30.51           3.60                 0.56  ...   
1  

In [14]:
#group by customer segment

In [15]:
df_by_segment=master_df.groupby('Customer_Segment')
print(df_by_segment)

In [16]:
#profit

In [17]:
print(df_by_segment['Profit'].sum())

Customer_Segment
CONSUMER          287959.94
CORPORATE         599746.00
HOME OFFICE       318354.03
SMALL BUSINESS    315708.01
Name: Profit, dtype: float64


In [24]:
a=df_by_segment['Profit'].sum().sort_values(ascending=True)
print(a)

Customer_Segment
CONSUMER          287959.94
SMALL BUSINESS    315708.01
HOME OFFICE       318354.03
CORPORATE         599746.00
Name: Profit, dtype: float64


In [25]:
print(pd.DataFrame(a))

                     Profit
Customer_Segment           
CONSUMER          287959.94
SMALL BUSINESS    315708.01
HOME OFFICE       318354.03
CORPORATE         599746.00


In [26]:
#Group by product category

In [29]:
by_product_category=master_df.groupby('Product_Category')
mean=by_product_category['Profit'].mean()
print(mean)

Product_Category
FURNITURE           68.116607
OFFICE SUPPLIES    112.369074
TECHNOLOGY         429.207516
Name: Profit, dtype: float64


In [30]:
#Group by product category with multiple columns

In [32]:
by_product_subcat=master_df.groupby(['Product_Category','Product_Sub_Category'])
mean=by_product_subcat['Profit'].mean()
print(mean)

Product_Category  Product_Sub_Category          
FURNITURE         BOOKCASES                         -177.683228
                  CHAIRS & CHAIRMATS                 387.693601
                  OFFICE FURNISHINGS                 127.446612
                  TABLES                            -274.411357
OFFICE SUPPLIES   APPLIANCES                         223.866498
                  BINDERS AND BINDER ACCESSORIES     335.970918
                  ENVELOPES                          195.864228
                  LABELS                              47.490174
                  PAPER                               36.949551
                  PENS & ART SUPPLIES                 11.950679
                  RUBBER BANDS                        -0.573575
                  SCISSORS, RULERS AND TRIMMERS      -54.161458
                  STORAGE & ORGANIZATION              12.205403
TECHNOLOGY        COMPUTER PERIPHERALS               124.389815
                  COPIERS AND FAX                   192

In [34]:
print(by_product_subcat['Profit'].count())

Product_Category  Product_Sub_Category          
FURNITURE         BOOKCASES                          189
                  CHAIRS & CHAIRMATS                 386
                  OFFICE FURNISHINGS                 788
                  TABLES                             361
OFFICE SUPPLIES   APPLIANCES                         434
                  BINDERS AND BINDER ACCESSORIES     915
                  ENVELOPES                          246
                  LABELS                             288
                  PAPER                             1225
                  PENS & ART SUPPLIES                633
                  RUBBER BANDS                       179
                  SCISSORS, RULERS AND TRIMMERS      144
                  STORAGE & ORGANIZATION             546
TECHNOLOGY        COMPUTER PERIPHERALS               758
                  COPIERS AND FAX                     87
                  OFFICE MACHINES                    337
                  TELEPHONES AND COMMUN

In [36]:
print(by_product_subcat['Profit'].max())

Product_Category  Product_Sub_Category          
FURNITURE         BOOKCASES                          7513.88
                  CHAIRS & CHAIRMATS                 8614.79
                  OFFICE FURNISHINGS                 3408.46
                  TABLES                             5626.42
OFFICE SUPPLIES   APPLIANCES                         5183.04
                  BINDERS AND BINDER ACCESSORIES    11535.28
                  ENVELOPES                          3187.37
                  LABELS                             1704.00
                  PAPER                              1480.15
                  PENS & ART SUPPLIES                 502.42
                  RUBBER BANDS                         84.10
                  SCISSORS, RULERS AND TRIMMERS      1094.74
                  STORAGE & ORGANIZATION             7606.00
TECHNOLOGY        COMPUTER PERIPHERALS               4833.27
                  COPIERS AND FAX                   13340.26
                  OFFICE MACHINES   

In [37]:
#REgions

In [41]:
print(master_df.groupby('Region').Profit.sum())

Region
ATLANTIC                 238960.66
NORTHWEST TERRITORIES    100653.08
NUNAVUT                    2841.11
ONTARIO                  346868.54
PRARIE                   321160.12
QUEBEC                   140426.65
WEST                     297008.61
YUKON                     73849.21
Name: Profit, dtype: float64


In [42]:
#Sales

In [49]:
print(master_df.groupby('Region').Sales.sum() / sum(master_df['Sales']))*100

Region
ATLANTIC                 0.135043
NORTHWEST TERRITORIES    0.053692
NUNAVUT                  0.007802
ONTARIO                  0.205370
PRARIE                   0.190224
QUEBEC                   0.101249
WEST                     0.241194
YUKON                    0.065426
Name: Sales, dtype: float64


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [50]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False)
    Create a spreadsheet-style pivot table as a DataFrame. The levels in
    the pivot table will be stored in MultiIndex objects (hierarchical
    indexes) on the index and columns of the result DataFrame.
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any o