In [16]:
#Counting letters
a="aagxghcnba"
count=0
for i in a:
    print(i,i.count(i))
    count=count+1
print(a.count("x"))

a 1
a 1
g 1
x 1
g 1
h 1
c 1
n 1
b 1
a 1
1


In [37]:
l=[1,2,3,'a','as',34]
print(tuple(l))
count=0
for i in l:
    count=count+1
    print(i,count)
print(count)

(1, 2, 3, 'a', 'as', 34)
1 1
2 2
3 3
a 4
as 5
34 6
6


In [38]:
a="s"
b="s"
print(a+b)

ss


In [56]:
S=" Python "
print(S.lstrip())
print(S.rstrip())
print(S.strip())

Python 
 Python
Python


In [60]:
a='1234'
print(a.isnumeric())

True


In [61]:
l=[1,2,3,4,"as"]
print(l[0])

1


In [66]:
l=[1,2,3,4,"as"]
for i in enumerate(l):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 'as')


In [73]:
l1=[1,2,3]
l2=[23,3,5]
a1=str(l1)
a2=str(l2)
print(str(a2+a1))

[23, 3, 5][1, 2, 3]


In [78]:
l1=[2,42,32,5,232]
l1.sort(reverse=True)
print(l1)

[232, 42, 32, 5, 2]


In [85]:
l1=[1,1,2,3,2,"a","a"]
l2=[]
if i in l1:
    l2.append(l1)
print(l2)

[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]
[[1, 1, 2, 3, 2, 'a', 'a']]


In [89]:
l1=[1,2,3]
l2=[1,2,3]
for i in l1:
    print(i)
for j in l2:
    print(j)
print(i+j)

1
2
3
1
2
3
6


In [100]:
d={'name':"pavan",'age':23}
d['id']=23
print(d)


{'name': 'pavan', 'age': 23, 'id': 23}


In [2]:
[ str(i) for i in range(0,5)]

['0', '1', '2', '3', '4']

In [3]:
def l(a,b):
    return a+b
l(2,3)

5

In [9]:
sum=lambda a,b:a+b
sum(2,3)

5

In [10]:
def gt(a,b):
    if a >b :
        print("a")
    else:
        print("b")
gt(3,4)

b


In [18]:
gt=lambda a,b:a if a>b else b  c
gt(4,5)

5

In [11]:
mylist=[1,2,3,4]
list(map(lambda n: f'number is {n}'  if n%2==0 else "odd",mylist))

['odd', 'number is 2', 'odd', 'number is 4']

In [11]:
class Student():
    name="pavan"
    place="hassan"
s1=Student()
print(s1.name,s1.place)

pavan hassan


In [17]:
class Student():
    def __init__(self,name,age,place):
        self.name=name
        self.age=age
        self.place=place
s1=Student("pavan",23,"hassan")
print(s1.name,s1.place,s1.age)
s1=Student("nayan",23,"hassan")
print(s1.name,s1.place,s1.age)

pavan hassan 23
nayan hassan 23


In [4]:
class Student():
    def __init__(self,name,age,place):
        self.name=name
        self.age=age
        self.place=place
    def school(self,language):
        self.language=language
        print(f'{self.name} school{language}')

s1=Student("pavan",23,"hassan")
print(s1.name,s1.place,s1.age)
s1=Student("nayan",23,"hassan")
print(s1.name,s1.place,s1.age)

print(s1.school(' kannada'))

pavan hassan 23
nayan hassan 23
nayan school kannada
None


In [10]:
class suhas():
    def __init__(self,name,age,place):
        self.name=name
        self.age=age
        self.place=place
s1=suhas('suhas',18,'mugali')
print(s1.name,s1.place,s1.age)

class manu(suhas):
    def __init__(self,name,age,place,school,year):
        suhas.__init__(self,name,age,place)
        self.school=school
        self.year=year
m1=manu('manu',16,'mugali','bgs',2021)
print(m1.school)

suhas mugali 18
bgs


In [23]:
a=5
for i in range(0,10):
    print(i)
    #print(i)
print(i.__sizeof__())

0
1
2
3
4
5
6
7
8
9
28


In [35]:
a=5
for i in range(5):
    print(i)
    yield a

SyntaxError: 'yield' outside function (<ipython-input-35-5e71d416b9dd>, line 4)

In [39]:
l=iter([1,2,3])
x=next(l)
print(x)
x=next(l)
print(x)

1
2


In [46]:
i=0
for i in range(3):
    print(list(i))
    

TypeError: 'int' object is not iterable

In [22]:
names={'suhas':18,'manu':16,'prajju':22}
#print(names)
for i in names.items():
    print(i)
names['pavan']=24
print(names)

('suhas', 18)
('manu', 16)
('prajju', 22)
{'suhas': 18, 'manu': 16, 'prajju': 22, 'pavan': 24}


In [26]:
a='pavan'
a.count('p')

1

In [39]:
a=[1,200,300,4,5]
a.sort()
print(a[-1])

300


In [58]:
def Sorted():
        Sorted.sort()
        return Sorted
Sorted(1,2,3,45)
#print(Sorted(a,b,c,d))

TypeError: Sorted() takes 0 positional arguments but 4 were given

In [70]:
def Sort(a,b,c,d):
    return Sort.sort()
print(Sort(1,2,3,4))
    

AttributeError: 'function' object has no attribute 'sort'

In [68]:
def su(a,b):
    return a+b
su(2,3)

5

In [75]:
def number(*a):
    for i in a:
        if i in range(3):
            print("yes")
        else:
            print("no")
    return number
print(number(7))

no
<function number at 0x00000249244E5EE0>


In [80]:
def Sort(*a):
    return Sort-
print(Sort([1,32,1]).sort())

AttributeError: 'function' object has no attribute 'sort'

In [2]:
l=[223.121,1232,23,334]
l.sort()
print(l)

[23, 223.121, 334, 1232]


In [16]:
import pandas as pd
num=pd.Series([1,2,3,4])
print(type(num),"   \n", num)

<class 'pandas.core.series.Series'>    
 0    1
1    2
2    3
3    4
dtype: int64


In [23]:
import pandas as pd
num=pd.Series(['1','a','b','c',23])
print( num)

0     1
1     a
2     b
3     c
4    23
dtype: object


In [26]:
import pandas as pd
num=pd.date_range(start='01-02-2021',end='03-02-2021')
print(num)

DatetimeIndex(['2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
               '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
               '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13',
               '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17',
               '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21',
               '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25',
               '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29',
               '2021-01-30', '2021-01-31', '2021-02-01', '2021-02-02',
               '2021-02-03', '2021-02-04', '2021-02-05', '2021-02-06',
               '2021-02-07', '2021-02-08', '2021-02-09', '2021-02-10',
               '2021-02-11', '2021-02-12', '2021-02-13', '2021-02-14',
               '2021-02-15', '2021-02-16', '2021-02-17', '2021-02-18',
               '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22',
               '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26',
      

In [27]:
import pandas as pd
num=pd.date_range('01-02-2021','03-02-2021')
print(num)

DatetimeIndex(['2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
               '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
               '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13',
               '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17',
               '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21',
               '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25',
               '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29',
               '2021-01-30', '2021-01-31', '2021-02-01', '2021-02-02',
               '2021-02-03', '2021-02-04', '2021-02-05', '2021-02-06',
               '2021-02-07', '2021-02-08', '2021-02-09', '2021-02-10',
               '2021-02-11', '2021-02-12', '2021-02-13', '2021-02-14',
               '2021-02-15', '2021-02-16', '2021-02-17', '2021-02-18',
               '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22',
               '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26',
      

In [32]:
a=["ASdsad"]
b=a.copy()
print(b)

['ASdsad']


In [ ]:

Data Structure	Dimensions	Description
Series	1	1D labeled homogeneous array, sizeimmutable.
Data Frames	2	General 2D labeled, size-mutable tabular structure with potentially heterogeneously typed columns.
Panel	3	General 3D labeled, size-mutable array.

In [39]:
import pandas as pd
num=pd.Series(['1','a','b','c',23])
for i in num.items():
    print(i)

(0, '1')
(1, 'a')
(2, 'b')
(3, 'c')
(4, 23)


In [48]:
import pandas as pd
a=pd.Series([1,2,3,4],index=[1,2,3,4])
print(a)

1    1
2    2
3    3
4    4
dtype: int64


In [51]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4])
data=pd.Series(a,index=[10,"v",12,13])
print(data)

10    1
v     2
12    3
13    4
dtype: int32


In [53]:
import pandas as pd
import numpy as np
a={1:1,2:34}
data=pd.Series(a)
print(data)

1     1
2    34
dtype: int64


In [56]:
import pandas as pd
d=pd.Series({1:2,2:1},index=[1,3])
print(d)

1    2.0
3    NaN
dtype: float64


In [62]:
import pandas as pd
df=pd.DataFrame({"name":['suhas','manu'],"year":[2000,2001],})
print(df)

    name  year
0  suhas  2000
1   manu  2001


In [72]:
import pandas as pd
file=pd.read_csv(r"C:\Users\Admin\Desktop\pavan\Ignited tech\simple.csv")
print(file.info)

<bound method DataFrame.info of      Month  Temp
0      jan    25
1      feb    23
2      mar    45>


In [73]:
import pandas as pd
mass=pd.Series([0.33,4.87,5.97,0.642,1898,568,86.8,102,0.0146],index=['Mercury','Venus','Earth','Mars','jupiter','Saturn','Uranus','Neptune','Plito'])
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Plito         0.0146
dtype: float64


In [89]:
print(mass*3)

Mercury       0.9900
Venus        14.6100
Earth        17.9100
Mars          1.9260
jupiter    5694.0000
Saturn     1704.0000
Uranus      260.4000
Neptune     306.0000
Plito         0.0438
dtype: float64


In [93]:
print(mass.Mercury<0.9900)

True


In [2]:
import pandas as pd
import numpy as np

n=np.random.randint(10,15,(4,3))
print(n)

[[14 10 13]
 [13 10 13]
 [11 12 13]
 [11 13 11]]


In [4]:
df=pd.DataFrame(n)
print(df)

    0   1   2
0  14  10  13
1  13  10  13
2  11  12  13
3  11  13  11
